### ISSUE TITLE
Idle and read timeouts should be configurable

### ISSUE THREAD

**Issue by abottchen** [puppetlabs/orchestrator_client-ruby#26]
## Use Case
CD4PE uses orchestrator_client as part of bolt to run jobs through the PE orchestrator.   Under heavy load, these connections can time out.  Unfortunately, the connection and read timeouts do not appear to be configurable, so the CD4PE jobs simply fail and users have no way to address the issue.

## Describe the Solution You Would Like
Make these timeouts configurable.  Otherwise, users are forced to manually update the code to work around issues with busy servers.  https://github.com/puppetlabs/orchestrator_client-ruby/blob/0.4.3/lib/orchestrator_client.rb#L35 is the idle timeout.  Adding `http.read_timeout` here will customize the read timeout from the default included in the Faraday gem of 60 seconds.  Wiring up overrides to these values that can be populated by bolt.yaml entries would be ideal.

## Describe Alternatives You've Considered
Users can change this code manually to get the desired effect.  Unfortunately, in the case of CD4PE, this is shipped as part of the container, and thus resets on each container restart.  So the user has to re-apply the patch each time.  It would be better as just part of the application.

**Comment by lucywyman** [comment]
I think we can close this as read_timeout is now configurable? https://github.com/puppetlabs/orchestrator_client-ruby/pull/27

**Comment by abottchen** [comment]
Yep, thanks!
